# Ref: https://alacritty.org/config-alacritty.html
[env]
TERM = "xterm-256color"

[window]
startup_mode = "Windowed"
dynamic_title = true
dimensions = { columns = 80, lines = 20 }
dynamic_padding = true
[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12.0
builtin_box_drawing = false
# rendering emoji https://github.com/alacritty/alacritty/issues/4692#issuecomment-855363642

[terminal]
shell = { program = "/usr/bin/zsh" }

[keyboard]
bindings = [
    # Copy and paste
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    { key = "Insert", mods = "Shift", action = "PasteSelection" },
    # font 
    { key = "Key0", mods = "Control", action = "ResetFontSize" },
    { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
    # window
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
    { key = "Q", mods = "Control|Shift", action = "Quit" },
    { key = "M", mods = "Control|Shift", action = "Minimize" },
    # search 
    { key = "F", mods = "Control|Shift", action = "SearchForward" },
    { key = "B", mods = "Control|Shift", action = "SearchBackward" },
]

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
unfocused_hollow = true

# Powerlevel10k
[colors.primary]
background = "#181818"
foreground = "#d8d8d8"

[colors.normal]
black = "#171421"
red = "#C01C28"
green = "#26A269"
yellow = "#A2734C"
blue = "#12488B"
magenta = "#A347BA"
cyan = "#2AA1B3"
white = "#D0CFCC"

[colors.bright]
black = "#5E5C64"
red = "#F66151"
green = "#33DA7A"
yellow = "#E9AD0C"
blue = "#2A7BDE"
magenta = "#C061CB"
cyan = "#33C7DE"
white = "#FFFFFF"
