name: Build and Package Alacritty

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev

      - name: Build Alacritty
        run: |
          chmod +x scripts/build.sh
          sudo ./scripts/build.sh

      - name: Package Alacritty
        run: |
          chmod +x scripts/package.sh
          sudo ./scripts/package.sh

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: alacritty_*.deb
          tag_name: ${{ env.ALACRITTY_VERSION }}
          draft: false
          prerelease: false